[proxy]
proxy-nginx ansible_host=89.169.XXX.XXX ansible_user=debian ansible_ssh_private_key_file=~/.ssh/id_ed25519

[backend]
backend-nginx-1 ansible_host=89.169.YYY.YYY ansible_user=debian ansible_ssh_private_key_file=~/.ssh/id_ed25519
backend-nginx-2 ansible_host=89.169.ZZZ.ZZZ ansible_user=debian ansible_ssh_private_key_file=~/.ssh/id_ed25519
